namespace Game.Web;

/// <summary>
///     Fixed list of original-game asset files served as static content under wwwroot/Game and preloaded into the
///     in-browser virtual filesystem before the runtime boots. Must be regenerated by hand if files under
///     wwwroot/Game change; there is no directory-listing API to discover them at runtime from a static host.
/// </summary>
internal static class WebAssetManifest
{
    public static readonly string[] RelativePaths =
    [
        "ERBE.EXE",
        "ERBE.DAT",
        "ERBE.GAM",
        "en.txt",
        "GRAFIK/ANWALT.LBM",
        "GRAFIK/ANWALT_A.LBM",
        "GRAFIK/AUTO.LBM",
        "GRAFIK/BUS.LBM",
        "GRAFIK/COMPUTER.LBM",
        "GRAFIK/COMPUT_O.LBM",
        "GRAFIK/DISPLAY.LBM",
        "GRAFIK/EINK1_O.LBM",
        "GRAFIK/EINK2_O.LBM",
        "GRAFIK/EINKAUF1.LBM",
        "GRAFIK/EINKAUF2.LBM",
        "GRAFIK/FAHRRADA.LBM",
        "GRAFIK/FONT_VGA.LBM",
        "GRAFIK/GARTEN.LBM",
        "GRAFIK/GARTEN_O.LBM",
        "GRAFIK/GOEBEL.LBM",
        "GRAFIK/GOEBEL_O.LBM",
        "GRAFIK/HAUS.LBM",
        "GRAFIK/HAUS_O.LBM",
        "GRAFIK/HELD.LBM",
        "GRAFIK/HELD_S.LBM",
        "GRAFIK/IMBISS.LBM",
        "GRAFIK/IMBISS_O.LBM",
        "GRAFIK/INGE.LBM",
        "GRAFIK/INGE_O.LBM",
        "GRAFIK/KELLER.LBM",
        "GRAFIK/KELLER_O.LBM",
        "GRAFIK/KUECHE.LBM",
        "GRAFIK/KUECHE_O.LBM",
        "GRAFIK/OZON.LBM",
        "GRAFIK/OZON_A1.LBM",
        "GRAFIK/OZON_A2.LBM",
        "GRAFIK/TELEBUCH.LBM",
        "GRAFIK/TITEL.LBM",
        "GRAFIK/WOHNZIMM.LBM",
        "GRAFIK/WOHNZI_O.LBM"
    ];
}
